modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eon_lazy_patch"
version="${mod_version}"
displayName="${mod_name}"
authors="Eon"
description='''
为休闲整合包准备的轻量补丁模组，提供 Eon 终端装备、经验存储、恒能发电、ProjectE EMC 修正，以及 AE2 无限流体元件适配。
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.eon_lazy_patch]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="ae2"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="industrialforegoing"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="ifeu"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="mekanism"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="mysticalagriculture"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="projecte"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.eon_lazy_patch]]
modId="extendedae"
type="optional"
ordering="AFTER"
side="BOTH"
